groups:
  - name: log-metrics
    rules:
      # Generate metrics for HTTP error logs
      - record: log_entries_total
        expr: sum by (container, hostname, job) (count_over_time({job="docker"}[5m]))

      # Generate metrics for HTTP error logs (401, 403, 404, 500, 501, 502, 503)
      - record: log_http_errors_total
        expr: sum by (container, hostname, job) (count_over_time({job="docker", message=~".*401.*|.*403.*|.*404.*|.*500.*|.*501.*|.*502.*|.*503.*"}[5m]))

      # Generate metrics for general error logs
      - record: log_general_errors_total
        expr: sum by (container, hostname, job) (count_over_time({job="docker", message=~".*error.*|.*ERROR.*|.*failed.*|.*FAILED.*|.*exception.*|.*EXCEPTION.*|.*timeout.*|.*TIMEOUT.*|.*connection refused.*|.*CONNECTION REFUSED.*"}[5m]))

      # Generate metrics for authentication errors
      - record: log_auth_errors_total
        expr: sum by (container, hostname, job) (count_over_time({job="docker", message=~".*401.*|.*403.*|.*unauthorized.*|.*UNAUTHORIZED.*|.*forbidden.*|.*FORBIDDEN.*|.*authentication.*failed.*|.*AUTHENTICATION.*FAILED.*"}[5m]))

      # Generate metrics for server errors
      - record: log_server_errors_total
        expr: sum by (container, hostname, job) (count_over_time({job="docker", message=~".*500.*|.*502.*|.*503.*|.*504.*|.*505.*|.*internal.*server.*error.*|.*INTERNAL.*SERVER.*ERROR.*"}[5m]))

      # Generate metrics for client errors
      - record: log_client_errors_total
        expr: sum by (container, hostname, job) (count_over_time({job="docker", message=~".*400.*|.*404.*|.*405.*|.*406.*|.*408.*|.*409.*|.*410.*|.*411.*|.*412.*|.*413.*|.*414.*|.*415.*|.*416.*|.*417.*|.*418.*|.*422.*|.*423.*|.*424.*|.*425.*|.*426.*|.*428.*|.*429.*|.*431.*|.*451.*"}[5m])) 