  global:
    resolve_timeout: 5m
    slack_api_url: 'xxxxxx'
  route:
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h
    receiver: 'slack-notifications'
    routes:
      # Critical alerts go to Slack immediately
      - match:
          severity: critical
        receiver: 'slack-critical'
        continue: true
        group_wait: 0s
        repeat_interval: 5m
      
      # Warning alerts go to email
      - match:
          severity: warning
        receiver: 'email-notifications'
        continue: true
      
      # Business team alerts
      - match:
          team: business
        receiver: 'business-team'
        continue: true
      
      # Infrastructure team alerts
      - match:
          team: infrastructure
        receiver: 'infrastructure-team'
        continue: true
      
      # Services team alerts
      - match:
          team: services
        receiver: 'services-team'
        continue: true

  receivers:
    - name: 'slack-notifications'
      slack_configs:
        - channel: '#logs'
          title: '{{ .Status | toUpper }}: {{ .CommonLabels.alertname }}'
          text: |
            *Status:* {{ .Status | toUpper }}
            *Alert:* {{ .CommonLabels.alertname }}
            *Container:* {{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}
            *Host:* {{ if (index .Alerts 0).Labels.hostname }}{{ if contains (index .Alerts 0).Labels.hostname ":" }}bpay-logging-and-monitoring{{ else }}{{ (index .Alerts 0).Labels.hostname }}{{ end }}{{ else if .CommonLabels.hostname }}{{ if contains .CommonLabels.hostname ":" }}bpay-logging-and-monitoring{{ else }}{{ .CommonLabels.hostname }}{{ end }}{{ else if (index .Alerts 0).Labels.instance }}{{ if contains (index .Alerts 0).Labels.instance ":" }}bpay-logging-and-monitoring{{ else }}{{ (index .Alerts 0).Labels.instance }}{{ end }}{{ else if .CommonLabels.instance }}{{ if contains .CommonLabels.instance ":" }}bpay-logging-and-monitoring{{ else }}{{ .CommonLabels.instance }}{{ end }}{{ else }}bpay-logging-and-monitoring{{ end }}
            *Application:* {{ if (index .Alerts 0).Labels.app }}{{ (index .Alerts 0).Labels.app }}{{ else if .CommonLabels.app }}{{ .CommonLabels.app }}{{ else }}N/A{{ end }}
            *Description:* {{ (index .Alerts 0).Annotations.description }}
            <http://13.40.8.181:3000/explore?left=%5B%22now-1h%22%2C%22now%22%2C%22Loki%22%2C%7B%22expr%22%3A%22%7Bcontainer%3D'{{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}'%7D%22%7D%5D|View in Grafana/Loki>
          send_resolved: true
          icon_url: 'https://grafana.com/static/assets/img/logo_new_transparent_400x.png'
          actions:
            - type: button
              text: 'View in Grafana/Loki'
              url: "http://13.40.8.181:3000/explore?left=[\"now-1h\",\"now\",\"Loki\",{\"expr\":\"{container='{{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}'}\"}]"

    - name: 'slack-critical'
      slack_configs:
        - channel: '#logs'
          title: '🚨 CRITICAL: {{ .CommonLabels.alertname }}'
          text: |
            *Status:* {{ .Status | toUpper }}
            *Alert:* {{ .CommonLabels.alertname }}
            *Container:* {{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}
            *Host:* {{ if (index .Alerts 0).Labels.hostname }}{{ if contains (index .Alerts 0).Labels.hostname ":" }}bpay-logging-and-monitoring{{ else }}{{ (index .Alerts 0).Labels.hostname }}{{ end }}{{ else if .CommonLabels.hostname }}{{ if contains .CommonLabels.hostname ":" }}bpay-logging-and-monitoring{{ else }}{{ .CommonLabels.hostname }}{{ end }}{{ else if (index .Alerts 0).Labels.instance }}{{ if contains (index .Alerts 0).Labels.instance ":" }}bpay-logging-and-monitoring{{ else }}{{ (index .Alerts 0).Labels.instance }}{{ end }}{{ else if .CommonLabels.instance }}{{ if contains .CommonLabels.instance ":" }}bpay-logging-and-monitoring{{ else }}{{ .CommonLabels.instance }}{{ end }}{{ else }}bpay-logging-and-monitoring{{ end }}
            *Application:* {{ if (index .Alerts 0).Labels.app }}{{ (index .Alerts 0).Labels.app }}{{ else if .CommonLabels.app }}{{ .CommonLabels.app }}{{ else }}N/A{{ end }}
            *Description:* {{ (index .Alerts 0).Annotations.description }}
            <http://13.40.8.181:3000/explore?left=%5B%22now-1h%22%2C%22now%22%2C%22Loki%22%2C%7B%22expr%22%3A%22%7Bcontainer%3D'{{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}'%7D%22%7D%5D|View in Grafana/Loki>
          send_resolved: true
          icon_emoji: ':rotating_light:'
          actions:
            - type: button
              text: 'View in Grafana/Loki'
              url: "http://13.40.8.181:3000/explore?left=[\"now-1h\",\"now\",\"Loki\",{\"expr\":\"{container='{{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}'}\"}]"

    - name: 'email-notifications'

    - name: 'business-team'
      slack_configs:
        - channel: '#logs'
          title: '{{ .Status | toUpper }}: {{ .CommonLabels.alertname }}'
          text: |
            *Status:* {{ .Status | toUpper }}
            *Alert:* {{ .CommonLabels.alertname }}
            *Container:* {{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}
            *Host:* {{ if (index .Alerts 0).Labels.hostname }}{{ if contains (index .Alerts 0).Labels.hostname ":" }}bpay-logging-and-monitoring{{ else }}{{ (index .Alerts 0).Labels.hostname }}{{ end }}{{ else if .CommonLabels.hostname }}{{ if contains .CommonLabels.hostname ":" }}bpay-logging-and-monitoring{{ else }}{{ .CommonLabels.hostname }}{{ end }}{{ else if (index .Alerts 0).Labels.instance }}{{ if contains (index .Alerts 0).Labels.instance ":" }}bpay-logging-and-monitoring{{ else }}{{ (index .Alerts 0).Labels.instance }}{{ end }}{{ else if .CommonLabels.instance }}{{ if contains .CommonLabels.instance ":" }}bpay-logging-and-monitoring{{ else }}{{ .CommonLabels.instance }}{{ end }}{{ else }}bpay-logging-and-monitoring{{ end }}
            *Application:* {{ if (index .Alerts 0).Labels.app }}{{ (index .Alerts 0).Labels.app }}{{ else if .CommonLabels.app }}{{ .CommonLabels.app }}{{ else }}N/A{{ end }}
            *Description:* {{ (index .Alerts 0).Annotations.description }}
            <http://13.40.8.181:3000/explore?left=%5B%22now-1h%22%2C%22now%22%2C%22Loki%22%2C%7B%22expr%22%3A%22%7Bcontainer%3D'{{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}'%7D%22%7D%5D|View in Grafana/Loki>
          send_resolved: true

    - name: 'infrastructure-team'
      slack_configs:
        - channel: '#logs'
          title: '{{ .Status | toUpper }}: {{ .CommonLabels.alertname }}'
          text: |
            *Status:* {{ .Status | toUpper }}
            *Alert:* {{ .CommonLabels.alertname }}
            *Container:* {{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}
            *Host:* {{ if (index .Alerts 0).Labels.hostname }}{{ if contains (index .Alerts 0).Labels.hostname ":" }}bpay-logging-and-monitoring{{ else }}{{ (index .Alerts 0).Labels.hostname }}{{ end }}{{ else if .CommonLabels.hostname }}{{ if contains .CommonLabels.hostname ":" }}bpay-logging-and-monitoring{{ else }}{{ .CommonLabels.hostname }}{{ end }}{{ else if (index .Alerts 0).Labels.instance }}{{ if contains (index .Alerts 0).Labels.instance ":" }}bpay-logging-and-monitoring{{ else }}{{ (index .Alerts 0).Labels.instance }}{{ end }}{{ else if .CommonLabels.instance }}{{ if contains .CommonLabels.instance ":" }}bpay-logging-and-monitoring{{ else }}{{ .CommonLabels.instance }}{{ end }}{{ else }}bpay-logging-and-monitoring{{ end }}
            *Application:* {{ if (index .Alerts 0).Labels.app }}{{ (index .Alerts 0).Labels.app }}{{ else if .CommonLabels.app }}{{ .CommonLabels.app }}{{ else }}N/A{{ end }}
            *Description:* {{ (index .Alerts 0).Annotations.description }}
            <http://13.40.8.181:3000/explore?left=%5B%22now-1h%22%2C%22now%22%2C%22Loki%22%2C%7B%22expr%22%3A%22%7Bcontainer%3D'{{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}'%7D%22%7D%5D|View in Grafana/Loki>
          send_resolved: true

    - name: 'services-team'
      slack_configs:
        - channel: '#logs'
          title: '{{ .Status | toUpper }}: {{ .CommonLabels.alertname }}'
          text: |
            *Status:* {{ .Status | toUpper }}
            *Alert:* {{ .CommonLabels.alertname }}
            *Container:* {{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}
            *Host:* {{ if (index .Alerts 0).Labels.hostname }}{{ if contains (index .Alerts 0).Labels.hostname ":" }}bpay-logging-and-monitoring{{ else }}{{ (index .Alerts 0).Labels.hostname }}{{ end }}{{ else if .CommonLabels.hostname }}{{ if contains .CommonLabels.hostname ":" }}bpay-logging-and-monitoring{{ else }}{{ .CommonLabels.hostname }}{{ end }}{{ else if (index .Alerts 0).Labels.instance }}{{ if contains (index .Alerts 0).Labels.instance ":" }}bpay-logging-and-monitoring{{ else }}{{ (index .Alerts 0).Labels.instance }}{{ end }}{{ else if .CommonLabels.instance }}{{ if contains .CommonLabels.instance ":" }}bpay-logging-and-monitoring{{ else }}{{ .CommonLabels.instance }}{{ end }}{{ else }}bpay-logging-and-monitoring{{ end }}
            *Application:* {{ if (index .Alerts 0).Labels.app }}{{ (index .Alerts 0).Labels.app }}{{ else if .CommonLabels.app }}{{ .CommonLabels.app }}{{ else }}N/A{{ end }}
            *Description:* {{ (index .Alerts 0).Annotations.description }}
            <http://13.40.8.181:3000/explore?left=%5B%22now-1h%22%2C%22now%22%2C%22Loki%22%2C%7B%22expr%22%3A%22%7Bcontainer%3D'{{ if (index .Alerts 0).Labels.name }}{{ (index .Alerts 0).Labels.name }}{{ else if (index .Alerts 0).Labels.container }}{{ (index .Alerts 0).Labels.container }}{{ else if .CommonLabels.container }}{{ .CommonLabels.container }}{{ else }}N/A{{ end }}'%7D%22%7D%5D|View in Grafana/Loki>
          send_resolved: true

  inhibit_rules:
    # Inhibit critical alerts if the node is down
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'instance'] 