modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: "ip4"
      valid_status_codes: [200, 201, 202, 204]
      fail_if_ssl: false
      fail_if_not_ssl: false
      headers:
        User-Agent: "Prometheus/Blackbox Exporter"

  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      preferred_ip_protocol: "ip4"
      valid_status_codes: [200, 201, 202, 204]
      fail_if_ssl: false
      fail_if_not_ssl: false
      headers:
        User-Agent: "Prometheus/Blackbox Exporter"
        Content-Type: "application/json"
      body: '{"health": "check"}'

  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"

  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

  dns:
    prober: dns
    timeout: 5s
    dns:
      preferred_ip_protocol: "ip4"
      query_name: "kubernetes.default.svc.cluster.local" 